# yaml
tracing:
  log_level: info
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "slim-data-plane"
  drain_timeout: 10s

services:
  slim/0:
    pubsub:
      servers:
        - endpoint: "0.0.0.0:56400"
          tls:
            insecure: true
      clients: []
    controller:
      servers:
        - endpoint: "0.0.0.0:56401"
          tls:
            insecure: true