#!/usr/bin/env bash

set -euo pipefail

SUPPORTED_AGENTS="claude-code codex opencode copilot-cli"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
A2A_SEND_DIR="$SCRIPT_DIR/skills/a2a-messaging/scripts/a2a-send"
A2A_SEND_WRAPPER="$A2A_SEND_DIR/a2a-send"
A2A_SEND_BIN="$A2A_SEND_DIR/a2a-send.bin"

AGENT=""
SKIP_BUILD=0
SKILL_ROOT_OVERRIDE=""
VERBOSE=0

usage() {
	cat <<'EOF'
Usage:
	./install.sh <agent> [--skill-root <path>] [--skip-build] [--verbose]
	./install.sh --agent <agent> [--skill-root <path>] [--skip-build] [--verbose]

Supported CLI-native agents:
	- claude-code
	- codex
	- opencode
	- copilot-cli

What this initial installer does:
	1. Validates the target CLI-native agent name.
	2. Builds skills/a2a-messaging/scripts/a2a-send/a2a-send.bin.
	3. Installs bundled skills into the agent-specific skills directory.
	4. Warns when optional environment variables are missing.

Default skill directories:
	- claude-code: $CWD/.claude/skills
	- codex:       $CWD/.agents/skills
	- opencode:    $CWD/.opencode/skills
	- copilot-cli: not mapped yet; pass --skill-root <path>

Environment variables checked:
	- IDENTITY_API_SERVER_URL      Used by /check-identity.
	- IDENTITY_SERVICE_API_KEY     Used by /check-identity.
	- SLIM_SHARED_SECRET           Used by /a2a-send only for SLIM targets.

The installer also writes .agntcy/cli-native-agents/config.env with
AGNTCY_SKILLS_DIR so recruiter skills can create new skills in the same
agent-specific project directory.
EOF
}

info() {
	[ "$VERBOSE" -eq 1 ] || return 0
	printf '==> %s\n' "$*"
}

notice() {
	printf '==> %s\n' "$*"
}

warn() {
	printf 'WARNING: %s\n' "$*" >&2
}

die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

normalize_agent() {
	case "$1" in
		claude|claude-code)
			printf '%s\n' "claude-code"
			;;
		codex)
			printf '%s\n' "codex"
			;;
		opencode|open-code)
			printf '%s\n' "opencode"
			;;
		copilot|copilot-cli)
			printf '%s\n' "copilot-cli"
			;;
		*)
			return 1
			;;
	esac
}

prompt_for_agent() {
	cat <<'EOF'
Select the CLI-native agent to prepare for:
	1) claude-code
	2) codex
	3) opencode
	4) copilot-cli
EOF
	printf 'Agent [1-4]: '
	read -r choice

	case "$choice" in
		1|claude|claude-code) AGENT="claude-code" ;;
		2|codex) AGENT="codex" ;;
		3|opencode|open-code) AGENT="opencode" ;;
		4|copilot|copilot-cli) AGENT="copilot-cli" ;;
		*) die "unsupported selection: $choice" ;;
	esac
}

parse_args() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
			--agent|-a)
				[ "$#" -ge 2 ] || die "--agent requires a value"
				AGENT="$(normalize_agent "$2")" || die "unsupported agent: $2"
				shift 2
				;;
			--skill-root)
				[ "$#" -ge 2 ] || die "--skill-root requires a value"
				SKILL_ROOT_OVERRIDE="$2"
				shift 2
				;;
			--skip-build)
				SKIP_BUILD=1
				shift
				;;
			--verbose|-v)
				VERBOSE=1
				shift
				;;
			--help|-h)
				usage
				exit 0
				;;
			--*)
				die "unknown option: $1"
				;;
			*)
				[ -z "$AGENT" ] || die "only one agent can be specified"
				AGENT="$(normalize_agent "$1")" || die "unsupported agent: $1"
				shift
				;;
		esac
	done

	if [ -z "$AGENT" ]; then
		if [ -t 0 ]; then
			prompt_for_agent
		else
			usage
			exit 64
		fi
	fi
}

agent_skill_root() {
	if [ -n "$SKILL_ROOT_OVERRIDE" ]; then
		case "$SKILL_ROOT_OVERRIDE" in
			/*) printf '%s\n' "$SKILL_ROOT_OVERRIDE" ;;
			*) printf '%s/%s\n' "$(pwd)" "$SKILL_ROOT_OVERRIDE" ;;
		esac
		return 0
	fi

	case "$AGENT" in
		claude-code)
			printf '%s\n' "$(pwd)/.claude/skills"
			;;
		codex)
			printf '%s\n' "$(pwd)/.agents/skills"
			;;
		opencode)
			printf '%s\n' "$(pwd)/.opencode/skills"
			;;
		copilot-cli)
			return 1
			;;
	esac
}

quote_for_env() {
	value="$1"
	value="${value//\'/\'\\\'\'}"
	printf "'%s'" "$value"
}

write_project_config() {
	skill_root="$1"
	config_dir="$(pwd)/.agntcy/cli-native-agents"
	config_file="$config_dir/config.env"

	mkdir -p "$config_dir"
	{
		printf '# Generated by cli-native-agents/install.sh.\n'
		printf 'AGNTCY_CLI_AGENT=%s\n' "$(quote_for_env "$AGENT")"
		printf 'AGNTCY_SKILLS_DIR=%s\n' "$(quote_for_env "$skill_root")"
		printf 'AGNTCY_A2A_SEND=%s\n' "$(quote_for_env "$A2A_SEND_WRAPPER")"
	} > "$config_file"

	info "Wrote project config: $config_file"
}

copy_skill_dir() {
	source_dir="$1"
	dest_dir="$2"

	mkdir -p "$dest_dir"
	(
		cd "$source_dir"
		find . -mindepth 1 -maxdepth 1 -exec cp -R {} "$dest_dir" \;
	)
}

check_command() {
	command -v "$1" >/dev/null 2>&1
}

check_agent_cli() {
	case "$AGENT" in
		claude-code)
			if check_command claude; then
				info "Found Claude Code CLI: $(command -v claude)"
			else
				warn "Claude Code CLI not found in PATH; install it before using the prepared skills."
			fi
			;;
		codex)
			if check_command codex; then
				info "Found Codex CLI: $(command -v codex)"
			else
				warn "Codex CLI not found in PATH; install it before using the prepared skills."
			fi
			;;
		opencode)
			if check_command opencode; then
				info "Found opencode CLI: $(command -v opencode)"
			else
				warn "opencode CLI not found in PATH; install it before using the prepared skills."
			fi
			;;
		copilot-cli)
			if check_command gh && gh extension list 2>/dev/null | grep -q 'github/gh-copilot'; then
				info "Found GitHub Copilot CLI via gh extension."
			elif check_command copilot; then
				info "Found copilot command: $(command -v copilot)"
			else
				warn "Copilot CLI not found; install GitHub CLI with the gh-copilot extension before using the prepared skills."
			fi
			;;
	esac
}

check_common_tools() {
	if check_command dirctl; then
		info "Found dirctl: $(command -v dirctl)"
	else
		warn "dirctl not found in PATH; /recruit needs it for AGNTCY Directory Service discovery."
	fi

	if check_command jq; then
		info "Found jq: $(command -v jq)"
	else
		warn "jq not found in PATH; /recruit needs it to parse OASF records."
	fi

	if check_command python3; then
		info "Found python3: $(command -v python3)"
	elif check_command python; then
		info "Found python: $(command -v python)"
	else
		warn "python3 not found in PATH; /check-identity needs Python 3.7+ from the standard library."
	fi
}

is_placeholder_value() {
	case "$1" in
		""|"<"*|*REPLACE_WITH*|*your_agntcy_identity_service_api_key*)
			return 0
			;;
		*)
			return 1
			;;
	esac
}

check_env_var() {
	var_name="$1"
	reason="$2"
	value="${!var_name:-}"

	if is_placeholder_value "$value"; then
		warn "$var_name is not set to a usable value. $reason"
	else
		info "$var_name is set."
	fi
}

check_environment() {
	if [ "$VERBOSE" -eq 0 ]; then
		missing_env=0
		for var_name in IDENTITY_API_SERVER_URL IDENTITY_SERVICE_API_KEY SLIM_SHARED_SECRET; do
			value="${!var_name:-}"
			if is_placeholder_value "$value"; then
				missing_env=1
			fi
		done

		if [ "$missing_env" -eq 1 ]; then
			warn "Some optional environment variables are not set. See $SCRIPT_DIR/.env.example."
		fi
		return 0
	fi

	check_env_var "IDENTITY_API_SERVER_URL" "Required only by /check-identity."
	check_env_var "IDENTITY_SERVICE_API_KEY" "Required only by /check-identity."
	check_env_var "SLIM_SHARED_SECRET" "Required only when /a2a-send targets an agent that advertises SLIM/SLIMRPC. HTTP-only targets can ignore this."
}

build_a2a_send() {
	[ -d "$A2A_SEND_DIR" ] || die "a2a-send source directory not found: $A2A_SEND_DIR"
	[ -f "$A2A_SEND_DIR/main.go" ] || die "a2a-send main.go not found: $A2A_SEND_DIR/main.go"

	if [ "$SKIP_BUILD" -eq 1 ]; then
		info "Skipping a2a-send build (--skip-build)."
		[ -x "$A2A_SEND_WRAPPER" ] || chmod +x "$A2A_SEND_WRAPPER"
		return
	fi

	check_command go || die "Go is required to build a2a-send. Install Go 1.25+ and rerun this script."

	notice "Building a2a-send"
	info "Using $(go version)."
	(
		cd "$A2A_SEND_DIR"
		go build -o "$A2A_SEND_BIN" .
	)

	chmod +x "$A2A_SEND_WRAPPER" "$A2A_SEND_BIN"
	info "Built $A2A_SEND_BIN"
}

install_skills() {
	if ! skill_root="$(agent_skill_root)"; then
		die "no default skill directory is mapped for $AGENT yet. Re-run with --skill-root <path>."
	fi

	write_project_config "$skill_root"

	notice "Installing skills"
	info "Installing bundled skills into $skill_root"
	mkdir -p "$skill_root"

	for source_dir in "$SCRIPT_DIR"/skills/*; do
		[ -d "$source_dir" ] || continue
		skill_name="$(basename "$source_dir")"
		dest_dir="$skill_root/$skill_name"

		copy_skill_dir "$source_dir" "$dest_dir"
		info "Installed skill: $skill_name -> $dest_dir"
	done
}

main() {
	parse_args "$@"

	notice "Preparing $AGENT"
	check_agent_cli
	check_common_tools
	build_a2a_send
	install_skills
	check_environment

	cat <<EOF

Install check complete for $AGENT.

Skills directory:
	$(agent_skill_root)

EOF
}

main "$@"
