version: "3.8"
services:
  sqlite:
    image: busybox
    volumes:
      - hydra-sqlite:/mnt/sqlite
    command: "chmod -R 777 /mnt/sqlite"

  hydra:
    image: oryd/hydra:v2.3.0
    build:
      context: test
      dockerfile: .docker/Dockerfile-local-build
    ports:
      - "4444:4444"
      - "4445:4445"
      - "5555:5555"
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - hydra-sqlite:/mnt/sqlite:rw
      - type: bind
        source: ./config/hydra
        target: /etc/config/hydra
    pull_policy: missing
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - STRATEGIES_ACCESS_TOKEN=jwt
    restart: unless-stopped
    depends_on:
      - hydra-migrate
      - sqlite

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    build:
      context: test
      dockerfile: .docker/Dockerfile-local-build
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - STRATEGIES_ACCESS_TOKEN=jwt
    command: migrate -c /etc/config/hydra/hydra.yml sql up -e --yes
    pull_policy: missing
    volumes:
      - hydra-sqlite:/mnt/sqlite:rw
      - type: bind
        source: ./config/hydra
        target: /etc/config/hydra
    restart: on-failure
    depends_on:
      - sqlite

  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.3.0
    ports:
      - "3333:3333"
    restart: unless-stopped

  postgresd:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra

  identity-node:
    container_name: identity-node
    image: ghcr.io/agntcy/identity/node:latest
    restart: always
    depends_on:
      - identity-postgres
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - DB_HOST=identity-postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identity

  identity-postgres:
    image: postgres:latest
    container_name: identity-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=identity

volumes:
  hydra-sqlite:
  couchdb-data: