site_name: IOA Global Coffee
repo_url: https://github.com/cisco-outshift-ai-agents/ioa-global-coffee
repo_name: GitHub
docs_dir: docs

plugins:
  - search

nav:
  - README: index.md

theme:
  name: material
  font:
    text: "Roboto"
    code: "Roboto Mono"
  favicon: cascade.jpg

  # Display a link to edit pages right on GitHub
  features:
    - content.action.edit

  icon:
    logo: material/cog
    repo: simple/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

edit_uri: edit/main/docs/

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - toc:
      permalink: "#"
  - markdown.extensions.codehilite:
      guess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.highlight
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css