# SLIM v0.7+ requires to use debian trixie distribution
FROM astral/uv:0.11.16-python3.13-trixie-slim@sha256:d57fc364ed714127c162a01b316bfb7b9a3fd09d97c665781a5607acaa35d254

WORKDIR /app

# Silences warnings about not being able to link files since the cache and sync target are on separate file systems
ENV UV_LINK_MODE=copy

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=coffeeAGNTCY/coffee_agents/lungo/uv.lock,target=uv.lock \
    --mount=type=bind,source=coffeeAGNTCY/coffee_agents/lungo/pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

COPY coffeeAGNTCY/coffee_agents/lungo/ .

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

CMD ["uv", "run", "python", "agents/farms/brazil/farm_server.py"]
