FROM astral/uv:0.11.16-python3.13-trixie-slim@sha256:d57fc364ed714127c162a01b316bfb7b9a3fd09d97c665781a5607acaa35d254

WORKDIR /app
COPY coffeeAGNTCY/coffee_agents/lungo/pyproject.toml coffeeAGNTCY/coffee_agents/lungo/uv.lock ./
RUN uv sync --locked --no-editable

COPY coffeeAGNTCY/coffee_agents/lungo/ .
EXPOSE 8125
CMD ["uv", "run", "python", "agents/mcp_servers/weather_service.py"]
