# SLIM v0.7+ requires to use debian trixie distribution
FROM astral/uv:0.11.14-python3.12-trixie-slim@sha256:13b5883729ec534af5863facf5c40ac0869f2c124ad5620c9ed36fe7c03fa87d

# Install system dependencies, including curl, ping, and wget
RUN apt-get update && \
    apt-get install -y --no-install-recommends git curl wget iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY coffeeAGNTCY/coffee_agents/lungo/pyproject.toml coffeeAGNTCY/coffee_agents/lungo/uv.lock ./
RUN uv sync --locked --no-editable

COPY coffeeAGNTCY/coffee_agents/lungo/ .
CMD ["uv", "run", "python", "agents/supervisors/logistics/main.py"]
