{{- if .Values.config.workflowApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-api-key-secret
  namespace: {{ .Release.Namespace }}
stringData:
  WORKFLOW_API_KEY: {{ .Values.config.workflowApiKey | quote }}
{{- end }}
