services:
  agp:
    image: ghcr.io/agntcy/agp/gw:0.3.6
    container_name: agp-gateway
    environment:
      - PASSWORD=dummy_password
    volumes:
      - ./config:/config
    command: ["/gateway", "--config", "/config/base/server-config.yaml"]
    ports:
      - "46357:46357"

  supervisor-agent:
    container_name: supervisor-agent
    build: .
    environment:
      - AGP_GATEWAY_URL=http://agp-gateway:46357
    ports:
      - "8125:8125"
    depends_on:
      - agp
