apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  FARM_AGENT_HOST: "{{ .Values.config.farmAgentHost }}"
  FARM_AGENT_PORT: "{{ .Values.config.farmAgentPort }}"
  AZURE_OPENAI_ENDPOINT: "{{ .Values.config.azureOpenAiEndpoint }}"
  AZURE_OPENAI_DEPLOYMENT: "{{ .Values.config.azureOpenAiDeployment }}"
  AZURE_OPENAI_API_VERSION: "{{ .Values.config.azureOpenAiApiVersion }}"
  LLM_PROVIDER: "{{ .Values.config.llmProvider }}"
