apiVersion: apps/v1
kind: Deployment
metadata:
  name: lungo-logistics-auction-supervisor
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Values.appVersion }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lungo-logistics-auction-supervisor
      version: {{ .Values.appVersion }}
  template:
    metadata:
      labels:
        app: lungo-logistics-auction-supervisor
        version: {{ .Values.appVersion }}
    spec:
    {{ if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
    {{ end }}
      serviceAccountName: lungo-logistics-auction-supervisor-sa
      containers:
      - name: lungo-logistics-auction-supervisor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if .Values.resources.enabled }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        {{ end }}
        ports:
        - containerPort: {{ .Values.service.port }}
        {{ if .Values.probes.readinessProbeEnabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.endpoint }}
            port: {{ .Values.probes.port }}
          initialDelaySeconds: 20
          periodSeconds: 10
        {{ end }}
        {{ if .Values.probes.livenessProbeEnabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.endpoint }}
            port: {{ .Values.probes.port }}
          initialDelaySeconds: 20
          periodSeconds: 10
        {{ end }}
        envFrom:
          - configMapRef:
              name: lungo-logistics-auction-supervisor-configmap
        {{ if .Values.externalSecrets }}
          - secretRef:
              name: lungo-logistics-auction-supervisor-secrets
        {{ end }}