# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: logistic-shipper
appVersion: v1
replicaCount: 1

image:
  repository: ghcr.io/agntcy/coffee-agntcy/logistic-shipper
  tag: latest
  pullPolicy: Always
  pullSecret:

service:
  port: 9091

config:
  transportServerEndpoint: ""
  defaultMessageTransport: ""
  otlpHttpEndpoint: ""

# You can use your own config here for service account
serviceaccount:
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_ROLE_ARN


probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  port: 9091
  endpoint: /v1/health

resources:
  enabled: false
  limits:
    cpu: 2000m
    memory: 2500Mi
  requests:
    cpu: 200m
    memory: 500Mi
