FROM node:20-alpine

WORKDIR /app

# Install dependencies
RUN --mount=type=cache,target=/root/.npm \
    --mount=type=bind,source=coffeeAGNTCY/coffee_agents/corto/exchange/frontend/package.json,target=package.json \
    --mount=type=bind,source=coffeeAGNTCY/coffee_agents/corto/exchange/frontend/package-lock.json,target=package-lock.json \
    npm ci

# Copy application files, including assets
COPY coffeeAGNTCY/coffee_agents/corto/exchange/frontend/ .

# Build the frontend
RUN npm install --verbose
RUN npm run build --verbose

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npx", "serve", "-s", "dist", "-l", "3000"]
