# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: lungo-ui
appVersion: v1
replicaCount: 1

image:
  repository: ghcr.io/agntcy/coffee-agntcy/lungo-ui
  tag: latest
  pullPolicy: Always
  pullSecret:

service:
  port: 3000

config:
  exchangeAppApiUrl: ""

# serviceaccount:
#   annotations:
#     eks.amazonaws.com/role-arn: REPLACE_WITH_ROLE_ARN

ingress:
  enabled: true
  name: lungo-ui-ingress
  className: nginx
  host: lungo-ui-demo.outshift.io
  serviceName: lungo-ui-ingress
  servicePort: 3000
  tlsSecret: lungo-ui-ingress-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /

probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  port: 3000
  endpoint: /v1/health

resources:
  enabled: false
  limits:
    cpu: 2000m
    memory: 2500Mi
  requests:
    cpu: 200m
    memory: 500Mi
