# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: lungo-ui
appVersion: v1
replicaCount: 1

image:
  repository: ghcr.io/agntcy/coffee-agntcy/lungo-ui
  tag: latest
  pullPolicy: Always
  pullSecret:

service:
  port: 3000

config:
  exchangeAppApiUrl: ""
  logisticsAppApiUrl: ""

# You can use your own config here for service account
serviceaccount:
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_ROLE_ARN

# You can use your own ingress stack of operators and letsencrypt mechanism
ingress:
  enabled: false  # If set to true, configure the values below for your ingress setup
  name: ""
  className: ""
  host: ""
  serviceName: ""
  servicePort: ""
  tlsSecret: ""
  annotations: {}

probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  port: 3000
  endpoint: /v1/health

resources:
  enabled: false
  limits:
    cpu: 2000m
    memory: 2500Mi
  requests:
    cpu: 200m
    memory: 500Mi
