# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: lungo-ui
appVersion: v1
replicaCount: 1

environment:

image:
  repository: ghcr.io/agntcy/coffee-agntcy/lungo-ui
  tag: latest
  pullPolicy: Always
  pullSecret:

service:
  port: 3000

configs:
  env:
    data:
      VITE_AGENTIC_WORKFLOWS_API_KEY: TheAnswerIs42 # Must match WORKFLOW_API_KEY on the Agentic Workflows API.
      VITE_AGENTIC_WORKFLOWS_API_URL: http://127.0.0.1:9105
      VITE_AGENTIC_WORKFLOWS_DOCS_GITHUB_BRANCH: main
      VITE_DIRECTORY_SERVER_URL: http://127.0.0.1:8888
      VITE_DIRECTORY_VERSION: v1.0.0
      VITE_DISCOVERY_APP_API_URL: http://127.0.0.1:8882
      VITE_EXCHANGE_APP_API_URL: http://127.0.0.1:8000
      VITE_GRAFANA_URL: http://127.0.0.1:3001
      VITE_LOGISTICS_APP_API_URL: http://127.0.0.1:9090

# You can use your own config here for service account
serviceaccount:
  annotations:
    eks.amazonaws.com/role-arn: REPLACE_WITH_ROLE_ARN

# You can use your own ingress stack of operators and letsencrypt mechanism
ingress:
  enabled: false # If set to true, configure the values below for your ingress setup
  name: ""
  className: ""
  host: ""
  serviceName: ""
  servicePort: ""
  tlsSecret: ""
  annotations: {}

  extraIngresses:
    - name: ""
      enabled: false  # If set to true, configure the values below for the additional ingresses setup
      paths:
        - path: ""
          pathType: ""
      host: ""
      className: ""
      serviceName: ""
      servicePort: ""
      tlsSecret: ""
      annotations: {}

probes:
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  port: 3000
  endpoint: /v1/health

resources:
  enabled: false
  limits:
    cpu: 2000m
    memory: 2500Mi
  requests:
    cpu: 200m
    memory: 500Mi
