{{- range $configMapName, $configMapSpec := .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- if eq $configMapName "_" }}
  name: {{ $.Values.appName }}-configmap
{{- else }}
  name: {{ $.Values.appName }}-{{ $configMapName }}-configmap
{{- end }}
  namespace: {{ $.Release.Namespace }}
data:
{{- range $key, $value := $configMapSpec.data }}
{{- if kindIs "string" $value }}
  {{ $key }}: {{ $value | quote }}
{{- else }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- if eq $configMapName "env" }}
  env-config.js: |
    {{ include "lungo-ui.envConfigJs" $ }}
{{- end }}
{{- end }}
