name: Build and Push Exchange Server Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "refs/tags/v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Pre-cleanup Docker images
        run: docker system prune -af

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login only on push
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (main)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: coffeeAGNTCY/coffee_agents/corto/docker/Dockerfile.exchange
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/exchange-server:latest

      - name: Build and push Docker image (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: coffeeAGNTCY/coffee_agents/corto/docker/Dockerfile.exchange
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/exchange-server:${{ github.ref_name }}