name: Deploy docs

on:
  push:
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Copy top-level docs and assets
        run: |
          mkdir -p ./docs
          sed 's/docs\///g' README.md > docs/README.md
          cp CONTRIBUTING.md docs/
          [ -f CHANGELOG.md ] && cp CHANGELOG.md docs/ || true
          [ -f CODE_OF_CONDUCT.md ] && cp CODE_OF_CONDUCT.md docs/ || true
          [ -f LICENSE ] && cp LICENSE docs/ || true
          [ -f SECURITY.md ] && cp SECURITY.md docs/ || true
          # Copy images/assets if they exist
          [ -f assets/coffee_agntcy.png ] && cp assets/coffee_agntcy.png docs/assets/ || true

      - name: Deploy
        run: |
          pip install mkdocs-material
          mkdocs gh-deploy --force