name: Helm Push Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        chart:
          - name: corto-ui
            path: coffeeAGNTCY/coffee_agents/corto/deployment/helm/corto-ui
            package_name: corto-ui
          - name: corto-exchange
            path: coffeeAGNTCY/coffee_agents/corto/deployment/helm/exchange
            package_name: corto-exchange
          - name: corto-farm
            path: coffeeAGNTCY/coffee_agents/corto/deployment/helm/farm
            package_name: corto-farm
          - name: lungo-ui
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/ui
            package_name: lungo-ui
          - name: lungo-exchange
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/exchange
            package_name: lungo-exchange
          - name: brazil-farm
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/brazil-farm
            package_name: brazil-farm
          - name: colombia-farm
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/colombia-farm
            package_name: colombia-farm
          - name: vietnam-farm
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/vietnam-farm
            package_name: vietnam-farm
          - name: weather-mcp-server
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/weather-mcp-server
            package_name: weather-mcp-server
          - name: logistic-supervisor
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/logistic-supervisor
            package_name: logistic-supervisor
          - name: logistic-shipper
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/shipper
            package_name: logistic-shipper
          - name: logistic-accountant
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/accountant
            package_name: logistic-accountant
          - name: logistic-farm
            path: coffeeAGNTCY/coffee_agents/lungo/deployment/helm/logistic-farm
            package_name: logistic-farm



    steps:
    - name: Pre-cleanup Docker images
      run: docker system prune -af

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log Pull Request Event
      if: github.event_name == 'pull_request'
      run: echo "PR detected - Packaging Helm chart (no push)"

    - name: Log Push Event
      if: github.event_name == 'push'
      run: echo "Push to main - Packaging and pushing Helm chart"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Helm
      uses: azure/setup-helm@v4
      with:
        version: "3.12.1"

    - name: Helm lint
      run: helm lint ${{ matrix.chart.path }} --with-subcharts

    - name: Package Helm Chart
      id: package
      run: |
        CHART_VERSION=$(grep '^version:' ${{ matrix.chart.path }}/Chart.yaml | awk '{print $2}')
        helm package ${{ matrix.chart.path }} --dependency-update --version $CHART_VERSION
        echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT

    - name: Push Helm Chart
      if: github.event_name == 'push'
      run: |
        helm push ${{ matrix.chart.package_name }}-${{ steps.package.outputs.chart_version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/coffee_agntcy/helm
