name: Source lint

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    workflow_dispatch:

permissions: read-all

jobs:
    forbidden-strings:
        name: Forbidden strings
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Check for forbidden strings
              uses: ./.github/actions/check-forbidden-strings
              with:
                  strings_json: '[
                      "\u2013",
                      "\u2014"
                      ]' # Note: en dash (U+2013), em dash (U+2014).
                  error_message: "Forbidden string found."

    shell-lint:
        name: Shell lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Setup Task
              uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
              with:
                  version: "3.53.1"

            - name: Install shfmt
              run: |
                  curl -sSfL -o /usr/local/bin/shfmt \
                      https://github.com/mvdan/sh/releases/download/v3.14.1/shfmt_v3.14.1_linux_amd64
                  chmod +x /usr/local/bin/shfmt
                  shfmt --version

            - name: shellcheck --version
              run: shellcheck --version # preinstalled on ubuntu-latest runners

            - name: Lint shell scripts
              run: task shell:lint
