name: Version Override Test
on:
  workflow_dispatch: {}

jobs:
  integration:
    uses: agntcy/coffeeAgntcy/.github/workflows/test.yaml@integration-hook
    secrets: inherit
    with:
      pip_overrides: |
        httpx==0.27.2
      pip_constraints: |
        grpcio<1.65
      docker_overrides: |
        slim=ghcr.io/agntcy/slim:0.5.0
        # more examples:
        # grafana=grafana/grafana:11.2.0
        # nats=nats:2.10.17
